name: Send All Detections to Elastic
run-name: All Detections to Elastic

# The workflow must be manually triggered
on:
  workflow_dispatch:

jobs:
  send-detections:
    runs-on: ubuntu-latest
    # Create our environment variable (stores Elastic API key)
    env:
      ELASTIC_API: ${{ secrets.ELASTIC_API }}
    steps:
      - uses: actions/checkout@v4
      #
      # In case of error, force the python version used to run 
      # validation checks:
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.X.X'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install requests
      # Run the TOML to JSON validation script
      - run: python DetEng/toml_to_json.py
      - run: echo "Job status - ${{ job.status }}."
