[rule]
author = ["KC"]
rule_id = "10000000-4000-400a-b200-4a285d000000"
description = "Using Zeek HTTP data, we're looking for bat files sent across the network on a port other than 80"
from = "now-5m" #From changes the default lookback time, 6m is default
name = "Bat files observed in HTTP Traffic on Unusual Port"
risk_score = 21
severity = "low"
type = "query"

query = '''
event.dataset: zeek.http and url.extension: bat and not destination.port :80
'''

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[rule.threat.technique.subtechnique]]
id = "T1059.003"
name = "Windows Command Shell"
reference = "https://attack.mitre.org/techniques/T1059/003/"

[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"