[rule]
author = ["KC"]
rule_id = "10000000-4000-400a-b200-4a285d000007"
description = "Powershell execution via a BAT file"
from = "now-5m" #From changes the default lookback time, 6m is default
name = "PowerShell execution via a BAT file"
risk_score = 21
severity = "low"
type = "query"

query = '''
event.dataset :"windows.sysmon_operational" and process.command_line: powershell* and process.parent.name : "cmd.exe"
'''
note = ""

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[rule.threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
reference = "https://attack.mitre.org/techniques/T1059/001/"

[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
