[rule]
author = ["KC"]
rule_id = "10000000-4000-400a-b200-4a285d000009"
description = "Alerts when .ps1 files are added to autorun on bootup locations in the Registry"
from = "now-5m" #From changes the default lookback time, 6m is default
name = "Suspicious PowerShell Added to Windows Registry"
risk_score = 21
severity = "low"
type = "query"

query = '''
event.dataset: "windows.sysmon_operational" and event.action : "RegistryEvent (Value Set)" and registry.path : *Microsoft\\Windows\\CurrentVersion\\Run* and registry.data.strings : *ps1
'''
note = ""

[[rule.threat]] # Example of assigning TTPs
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1547"
name = "Boot or Logon Autostart Execution"
reference = "https://attack.mitre.org/techniques/T1547/"
[[rule.threat.technique.subtechnique]]
id = "T1547.001"
name = "Registry Run Keys / Startup Folder"
reference = "https://attack.mitre.org/techniques/T1547/001/"

[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
