[rule]
author = ["KC"]
rule_id = "10000000-4000-400a-b200-4a285d000002"
description = "This triggers on .zip files transferred via FTP"
from = "now-5m" #From changes the default lookback time, 6m is default
name = "Data Exfiltration Observed via FTP"
risk_score = 75
severity = "medium"
type = "query"

query = '''
event.dataset : zeek.ftp and event.action : "STOR"  and zeek.ftp.arg : *.zip
'''
note = ""

[[rule.threat]] 
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1020"
name = "Automated Exfiltration"
reference = "https://attack.mitre.org/techniques/T1020/"

[rule.threat.tactic]
id = "TA0010"
name = "Exfiltration"
reference = "https://attack.mitre.org/tactics/TA0010/"