[rule]
author = ["KC"]
rule_id = "10000000-4000-400a-b200-4a285d000004"
description = "Alert triggers when more than 1000 queries are sent to a web server within a 5 minute period"
from = "now-5m" #From changes the default lookback time, 6m is default
name = "Excessive Web Traffic"
risk_score = 12
severity = "medium"
type = "threshold"

query = '''
event.dataset: "zeek.http" 
'''

[rule.threshold]
field = ["source.ip"]
value = 1000

[[rule.threat]] 
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"

[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"
