[rule]
author = ["KC"]
rule_id = "10000000-4000-400a-b200-4a285d000250"
description = "Example alert"
from = "now-5m" #From changes the default lookback time, 6m is default
name = "Test Alert"
risk_score = 3
severity = "low"
type = "query"

query = '''
event.dataset: "windows.sysmon_operational"
'''
note = ""

[[rule.threat]] # Example of assigning TTPs
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1547"
name = "Boot or Logon Autostart Execution"
reference = "https://attack.mitre.org/techniques/T1547/"
[[rule.threat.technique.subtechnique]]
id = "T1547.001"
name = "Registry Run Keys / Startup Folder"
reference = "https://attack.mitre.org/techniques/T1547/001/"

[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
