name: TOML and MITRE Validation
run-name: Validating TOML files

# The workflow can be manually triggered
# Also triggers on every push to main including a TOML file
on:
  push:
    branches: [ main ]
    paths:
      - 'DetEng/custom_detections/**'
      - '**.toml'
  workflow_dispatch:

jobs:
  toml-validation-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #
      # In case of error, force the python version used to run 
      # validation checks:
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.X.X'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install requests
      # Run the TOML validation and MITRE scripts
      - run: python DetEng/toml_validator.py
      - run: python DetEng/create_mitre.py
      - run: echo "Job status - ${{ job.status }}."
